version: '3'

services:
  # Веб-сервер который будем тестирвоать.
  nginx:
    image: nginx
    ports:
      - "80:80"
    networks:
      - backend

  # Веб-раузер которым будем тестировать.
  selenium:
    image: selenium/standalone-chrome
    ports:
      - "4444:4444"
    networks:
      - backend

networks:
  backend:
